test:
  num_layers: 5
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-05
  weight_decay: 1.0e-05
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.5
  tau_g: 0.5
  tau_m: 1.0
  w_g: 4
  w_m: 1
  epochs: 1000
  batch_size_1: null
  batch_size_2: null
